// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: pkg/pb/movetechdata.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MoveTechAdminProtoServiceClient is the client API for MoveTechAdminProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoveTechAdminProtoServiceClient interface {
	SaveProduct(ctx context.Context, in *SaveProductRequest, opts ...grpc.CallOption) (*SaveProductResponse, error)
}

type moveTechAdminProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMoveTechAdminProtoServiceClient(cc grpc.ClientConnInterface) MoveTechAdminProtoServiceClient {
	return &moveTechAdminProtoServiceClient{cc}
}

func (c *moveTechAdminProtoServiceClient) SaveProduct(ctx context.Context, in *SaveProductRequest, opts ...grpc.CallOption) (*SaveProductResponse, error) {
	out := new(SaveProductResponse)
	err := c.cc.Invoke(ctx, "/api.MoveTechAdminProtoService/SaveProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoveTechAdminProtoServiceServer is the server API for MoveTechAdminProtoService service.
// All implementations must embed UnimplementedMoveTechAdminProtoServiceServer
// for forward compatibility
type MoveTechAdminProtoServiceServer interface {
	SaveProduct(context.Context, *SaveProductRequest) (*SaveProductResponse, error)
	mustEmbedUnimplementedMoveTechAdminProtoServiceServer()
}

// UnimplementedMoveTechAdminProtoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMoveTechAdminProtoServiceServer struct {
}

func (UnimplementedMoveTechAdminProtoServiceServer) SaveProduct(context.Context, *SaveProductRequest) (*SaveProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveProduct not implemented")
}
func (UnimplementedMoveTechAdminProtoServiceServer) mustEmbedUnimplementedMoveTechAdminProtoServiceServer() {
}

// UnsafeMoveTechAdminProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoveTechAdminProtoServiceServer will
// result in compilation errors.
type UnsafeMoveTechAdminProtoServiceServer interface {
	mustEmbedUnimplementedMoveTechAdminProtoServiceServer()
}

func RegisterMoveTechAdminProtoServiceServer(s grpc.ServiceRegistrar, srv MoveTechAdminProtoServiceServer) {
	s.RegisterService(&MoveTechAdminProtoService_ServiceDesc, srv)
}

func _MoveTechAdminProtoService_SaveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveTechAdminProtoServiceServer).SaveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MoveTechAdminProtoService/SaveProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveTechAdminProtoServiceServer).SaveProduct(ctx, req.(*SaveProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoveTechAdminProtoService_ServiceDesc is the grpc.ServiceDesc for MoveTechAdminProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoveTechAdminProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.MoveTechAdminProtoService",
	HandlerType: (*MoveTechAdminProtoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveProduct",
			Handler:    _MoveTechAdminProtoService_SaveProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/movetechdata.proto",
}
